import { StyleSheet } from 'react-native'
import { UIConfig } from '../../config/UIConfig'
import { globalStyles } from '../../config/theme'

export const createAvatarScreenStyles = (
  avatarConfig: UIConfig['avatarSelection'],
  avatarWidth: number,
  hasGoBack: boolean,
  isInitialSelection: boolean
) =>
  StyleSheet.create({
    screen: {
      flex: 1,
    },
    backgroundImage: {
      flex: 1,
      width: '100%',
    },
    backgroundImageStyle: {
      opacity: 1,
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: avatarConfig.screenPaddingHorizontal,
      paddingTop: avatarConfig.paddingTop,
      paddingBottom: avatarConfig.buttonPaddingTop + 60, // Extra space to ensure button is visible
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      marginBottom: 20,
      paddingHorizontal: avatarConfig.titlePaddingHorizontal,
    },
    logo: {
      width: 50,
      height: 50,
      marginRight: 12,
      marginBottom: 4,
    },
    titleBox: {
      ...globalStyles.selectionTitleBox,
      ...globalStyles.shadow,
      ...globalStyles.elevation,
    },
    title: {
      fontFamily: 'Roboto',
      fontWeight: '700',
      fontStyle: 'normal',
      fontSize: avatarConfig.titleFontSize,
      lineHeight: avatarConfig.titleLineHeight,
      letterSpacing: 0,
      marginBottom: 8,
    },
    subtitle: {
      fontFamily: 'Roboto',
      fontWeight: '400',
      fontStyle: 'normal',
      fontSize: avatarConfig.subtitleFontSize,
      lineHeight: avatarConfig.subtitleLineHeight,
      letterSpacing: 0,
    },
    avatars: {
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginBottom: 20,
      paddingHorizontal: avatarConfig.itemsContainerPaddingHorizontal,
      width: '100%',
    },
    avatar: {
      height: avatarConfig.avatarSize.height,
      marginLeft: 0,
      marginRight: 0,
      marginVertical: avatarConfig.avatarMarginVertical,
    },
    avatarBody: {
      borderWidth: 0,
      overflow: 'visible',
      width: '100%',
      height: '100%',
      borderRadius: avatarConfig.avatarBorderRadius,
      position: 'relative',
    },
    imageWrapper: {
      width: '100%',
      height: '100%',
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarSelectedBorderOverlay: {
      position: 'absolute',
      borderColor: '#4CAF50',
      borderWidth: avatarConfig.borderWidth,
      borderRadius: avatarConfig.avatarBorderRadius,
      pointerEvents: 'none',
      zIndex: 1,
    },
    check: {
      position: 'absolute',
      zIndex: 10,
      backgroundColor: '#A4D233',
      borderRadius: (avatarConfig.iconSize * 2) / 2,
      width: avatarConfig.iconSize * 2,
      height: avatarConfig.iconSize * 2,
      justifyContent: 'center',
      alignItems: 'center',
      // Position icon half in, half out - offset by half icon size
      right: avatarConfig.iconSize * 0.5,
      top: avatarConfig.iconSize * 0.5,
    },
    editIconContainer: {
      position: 'absolute',
      backgroundColor: '#A4D233',
      borderRadius: (avatarConfig.iconSize * 2) / 2,
      width: avatarConfig.iconSize * 2,
      height: avatarConfig.iconSize * 2,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
      // Position icon half in, half out - offset by half icon size
      right: avatarConfig.iconSize * 0.5,
      top: avatarConfig.iconSize * 0.5,
    },
    avatarImage: {
      width: '100%',
      height: '88%',
      alignSelf: 'center',
      marginTop: 10,
      aspectRatio: 1,
      borderRadius: avatarConfig.avatarBorderRadius,
      overflow: 'visible',
      position: 'relative',
    },
    friendAvatarImage: {
      width: '100%',
      height: '100%',
      alignSelf: 'center',
      marginTop: 0,
      borderRadius: avatarConfig.avatarBorderRadius,
      overflow: 'visible',
      position: 'relative',
    },
    friendAvatarContainer: {
      width: '100%',
      height: '100%',
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    avatarPreviewContainer: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      top: 0,
      left: 0,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingBottom: 0,
    },
    avatarPreview: {
      position: 'absolute',
      bottom: -(avatarConfig.avatarSize.height * 0.7),
      alignSelf: 'center',
    },
    // Outer container for green border (when selected/active)
    avatarOuterContainer: {
      width: '100%',
      height: '100%',
      position: 'relative',
      borderRadius: avatarConfig.avatarBorderRadius,
      padding: 2, // Space for green border
    },
    // Inner container for white border
    avatarInnerContainer: {
      width: '100%',
      height: '100%',
      borderRadius: avatarConfig.avatarBorderRadius,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
    },
    // Green border wrapper (only when selected/active)
    avatarGreenBorder: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: avatarConfig.avatarBorderRadius,
      borderWidth: 2,
      borderColor: '#A4D233',
      pointerEvents: 'none',
    },
    standardAvatarSvgContainer: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    friendAvatarContainer: {
      width: '100%',
      height: '100%',
      position: 'relative',
    },
    name: {
      position: 'absolute',
      top: 20,
      left: 0,
      width: '100%',
      fontFamily: 'Roboto',
      fontWeight: '700',
      fontStyle: 'normal',
      textAlign: 'center',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0,
    },
    lockedAvatar: {
      opacity: 0.6,
    },
    lockOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      borderRadius: avatarConfig.avatarBorderRadius,
    },
    reminderBox: {
      flexDirection: 'row',
      ...globalStyles.messageBox,
      borderTopLeftRadius: 0,
      marginBottom: 20,
      marginHorizontal: 12,
      alignItems: 'flex-start',
      ...globalStyles.shadow,
      ...globalStyles.elevation,
    },
    reminderIconContainer: {
      marginRight: 10,
      marginTop: 2,
    },
    reminderIcon: {
      width: avatarConfig.reminderIconSize,
      height: avatarConfig.reminderIconSize,
    },
    reminderText: {
      flex: 1,
      fontFamily: 'Roboto',
      fontWeight: '400',
      fontStyle: 'normal',
      fontSize: avatarConfig.reminderFontSize,
      lineHeight: avatarConfig.reminderLineHeight,
      letterSpacing: 0,
    },
    buttonContainer: {
      flexDirection: 'row',
      paddingHorizontal: avatarConfig.buttonPaddingHorizontal,
      paddingTop: avatarConfig.buttonPaddingTop,
      paddingBottom: avatarConfig.buttonPaddingBottom,
      width: '100%',
      justifyContent: 'center',
      gap: 12,
    },
  })

