version: '3.4'
services:
  base:
    image: oky/base
    build:
      context: .
    command: /bin/true
  api:
    build:
      context: packages/api/.
    ports:
      - 3000:3000
    env_file: packages/api/.env
    depends_on:
      - base
  cms:
    build:
      context: packages/cms/.
    ports:
      - 5000:5000
    env_file: packages/cms/.env
    depends_on:
      - base
  postgres:
    image: postgres:10-alpine
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=periodtracker
      - POSTGRES_USER=periodtracker
      - POSTGRES_PASSWORD=periodtracker
volumes:
  db-data: {}
