import { StyleSheet } from 'react-native'
import type { UIConfig } from '../../config/UIConfig'
import { globalStyles } from '../../config/theme'
import { scaleHorizontal, getResponsiveValue } from '../../utils/responsive'

export const createCustomAvatarStyles = (
  config: UIConfig['avatarCustomization'],
  avatarSelectionConfig: UIConfig['avatarSelection'],
  screenWidth?: number
) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: 0,
      overflow: 'hidden',
      width: '100%',
      maxWidth: '100%',
      alignItems: 'center', // Center content on large screens
    },
    scrollView: {
      flex: 1,
      width: '100%',
      maxWidth: 1200, // Cap at 1200px for large tablets
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: config.spacing.medium,
      width: '100%',
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      marginBottom: config.spacing.medium,
      paddingHorizontal: screenWidth 
        ? (getResponsiveValue(screenWidth, {
            md: 14,
            lg: avatarSelectionConfig.titlePaddingHorizontal,
          }) || avatarSelectionConfig.titlePaddingHorizontal)
        : avatarSelectionConfig.titlePaddingHorizontal,
      paddingTop: avatarSelectionConfig.paddingTop,
    },
    titleBox: {
      flex: 1,
    },
    title: {
      fontFamily: 'Roboto',
      fontWeight: '700',
      fontStyle: 'normal',
      fontSize: avatarSelectionConfig.titleFontSize * 1.15,
      lineHeight: avatarSelectionConfig.titleLineHeight * 1.15,
      letterSpacing: 0,
      marginBottom: config.spacing.small,
    },
    subtitle: {
      fontFamily: 'Roboto',
      fontWeight: '400',
      fontStyle: 'normal',
      fontSize: avatarSelectionConfig.subtitleFontSize * 1.15,
      lineHeight: avatarSelectionConfig.subtitleLineHeight * 1.15,
      letterSpacing: 0,
    },
    whiteCard: {
      borderRadius: config.spacing.medium,
      paddingTop: config.spacing.medium,
      paddingHorizontal: config.paddingHorizontal,
      paddingBottom: config.spacing.small,
      marginLeft: config.paddingHorizontal,
      marginRight: config.paddingHorizontal,
      marginBottom: 0,
      alignSelf: 'stretch',
      overflow: 'hidden',
    },
    tutorialButton: {
      position: 'absolute',
      top: config.spacing.small,
      left: config.spacing.medium,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: config.spacing.small,
      paddingVertical: config.spacing.small / 2,
      borderRadius: config.spacing.medium,
      backgroundColor: '#E3F2FD',
      zIndex: 10,
      gap: config.spacing.small / 2,
    },
    tutorialButtonText: {
      fontSize: avatarSelectionConfig.subtitleFontSize,
      fontWeight: '600',
      color: '#2196F3',
    },
    avatarContainer: {
      width: '100%',
      height: config.avatarPreviewSize.height + config.spacing.medium,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: config.spacing.medium + config.spacing.small,
      borderRadius: config.spacing.small,
    },
    avatarPreview: {
      width: config.avatarPreviewSize.width,
      height: config.avatarPreviewSize.height,
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarLayer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    bodyColorBackground: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
    },
    avatarPartImage: {
      width: '100%',
      height: '100%',
      position: 'absolute',
      top: 0,
      left: 0,
    },
    categoryContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // Reduced vertical gap between icons and content
      marginBottom: config.spacing.medium,
      paddingHorizontal: 0,
    },
    categoryButton: {
      alignItems: 'center',
      flex: 1,
    },
    categoryButtonSelected: {
      // Selected styling handled by icon
    },
    categoryIcon: {
      width: config.categoryIconSize,
      height: config.categoryIconSize,
      borderRadius: config.categoryIconSize / 2,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: config.spacing.small,
    },
    categoryIconSelected: {
      backgroundColor: '#2196F3',
    },
    categoryIconUnselected: {
      backgroundColor: '#E3F2FD',
    },
    categoryIconImage: {
      width: config.categoryIconSize / 2,
      height: config.categoryIconSize / 2,
    },
    categoryIconImageSelected: {
      tintColor: '#fff',
    },
    categoryLabel: {
      fontSize: avatarSelectionConfig.subtitleFontSize * 0.75,
      color: '#424242',
    },
    optionsContainer: {
      paddingTop: config.spacing.small,
      paddingBottom: 0,
      overflow: 'visible',
    },
    optionSection: {
      marginBottom: config.spacing.medium,
    },
    lastOptionSection: {
      marginBottom: 0,
      paddingBottom: 0,
    },
    optionTitleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: config.spacing.medium,
      paddingHorizontal: 0,
    },
    optionTitle: {
      fontSize: avatarSelectionConfig.subtitleFontSize,
      fontWeight: 'bold',
      color: '#424242',
      marginBottom: 0,
    },
    arrowButtons: {
      flexDirection: 'row',
      gap: config.spacing.small,
    },
    arrowButton: {
      width: avatarSelectionConfig.iconSize * 3.2,
      height: avatarSelectionConfig.iconSize * 3.2,
      borderRadius: avatarSelectionConfig.iconSize * 1.6,
      backgroundColor: '#E3F2FD',
      alignItems: 'center',
      justifyContent: 'center',
    },
    arrowButtonDisabled: {
      opacity: 0.5,
    },
    paginatedOptions: {
      flexDirection: 'row',
      gap: config.optionImageGap,
      justifyContent: 'flex-start',
      alignItems: 'center',
    },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'flex-start',
      gap: config.spacing.small,
    },
    colorSwatches: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      paddingHorizontal: 0,
      overflow: 'visible',
    },
    colorSwatch: {
      width: config.colorSwatchSize,
      height: config.colorSwatchSize,
      borderRadius: config.colorSwatchSize / 2,
      borderWidth: avatarSelectionConfig.borderWidth,
      borderColor: 'transparent',
    },
    colorSwatchSelected: {
      borderColor: '#4CAF50',
    },
    bodyTypeContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: config.bodyTypeGap,
      paddingBottom: 0,
      marginBottom: 0,
      width: '100%',
      justifyContent: 'center',
    },
    bodyTypeOption: {
      width: config.bodyTypeSize.width,
      height: config.bodyTypeSize.height,
      borderRadius: config.spacing.small,
      borderWidth: avatarSelectionConfig.borderWidth,
      borderColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
    },
    bodyTypeOptionSelected: {
      borderColor: '#4CAF50',
    },
    bodyTypeImageContainer: {
      width: 60,
      height: 100,
      position: 'relative',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'visible',
    },
    bodyTypeImageBackground: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
      borderRadius: config.spacing.small / 2,
    },
    bodyTypeImage: {
      width: config.bodyTypeSize.width - config.spacing.small,
      height: config.bodyTypeSize.height - config.spacing.small,
      position: 'relative',
      zIndex: 1,
    },
    hairstyleOption: {
      width: config.optionImageSize.width,
      height: config.optionImageSize.height,
      borderRadius: config.spacing.small,
      borderWidth: avatarSelectionConfig.borderWidth,
      borderColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
    },
    hairstyleOptionSelected: {
      borderColor: '#4CAF50',
    },
    hairstyleImage: {
      width: config.optionImageSize.width - config.spacing.small,
      height: config.optionImageSize.height - config.spacing.small,
    },
    eyeShapeOption: {
      width: config.optionImageSize.width,
      height: config.optionImageSize.width,
      borderRadius: config.spacing.small,
      borderWidth: avatarSelectionConfig.borderWidth,
      borderColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
    },
    eyeShapeOptionSelected: {
      borderColor: '#4CAF50',
    },
    eyeShapeImage: {
      width: config.optionImageSize.width - config.spacing.small,
      height: config.optionImageSize.width - config.spacing.small,
    },
    itemOption: {
      width: '30%',
      aspectRatio: 1,
      borderRadius: config.spacing.small,
      borderWidth: avatarSelectionConfig.borderWidth,
      borderColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
    },
    itemOptionSelected: {
      borderColor: '#4CAF50',
    },
    itemImage: {
      width: '96%',
      height: '80%',
    },
    bottomButtonsContainer: {
      width: '100%',
      maxWidth: '100%',
      paddingHorizontal: config.spacing.medium,
      paddingTop: config.spacing.small,
      paddingBottom: config.spacing.medium,
      backgroundColor: '#E3F2FD',
      flexShrink: 0,
      overflow: 'hidden',
      marginTop: config.spacing.small,
    },
    bottomButtonsShadow: {
      position: 'absolute',
      top: -4,
      left: 16,
      right: 16,
      height: 4,
      backgroundColor: 'rgba(0, 0, 0, 0.25)',
      borderRadius: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 4,
    },
    bottomButtons: {
      flexDirection: 'row',
      gap: config.spacing.small,
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    exitButton: {
      minWidth: config.spacing.medium * 6.25,
      maxWidth: config.spacing.medium * 7.5,
      paddingVertical: config.spacing.medium,
      paddingHorizontal: config.spacing.medium * 1.25,
      borderRadius: config.spacing.small,
      justifyContent: 'center',
      alignItems: 'center',
    },
    saveButton: {
      minWidth: config.spacing.medium * 11.25,
      maxWidth: config.spacing.medium * 13.75,
      paddingVertical: config.spacing.medium,
      paddingHorizontal: config.spacing.medium * 1.25,
      borderRadius: config.spacing.small,
      justifyContent: 'center',
      alignItems: 'center',
    },
    orangeButton: {
      backgroundColor: '#FF9800',
    },
    buttonText: {
      color: '#fff',
      fontSize: avatarSelectionConfig.subtitleFontSize,
      lineHeight: avatarSelectionConfig.subtitleLineHeight,
      fontWeight: 'bold',
    },
    nameModal: {
      backgroundColor: '#fff',
      borderRadius: screenWidth && screenWidth >= 840 ? 24 : 20,
      padding: config.spacing.medium * 1.5,
      paddingTop: config.spacing.medium * 3.5,
      width: screenWidth && screenWidth >= 840 
        ? Math.min(screenWidth * 0.9, 600) 
        : (screenWidth ? screenWidth * 0.95 : scaleHorizontal(320)),
      maxWidth: screenWidth && screenWidth >= 840 ? 600 : undefined,
      minWidth: undefined,
    },
    modalTitle: {
      fontSize: avatarSelectionConfig.titleFontSize,
      fontWeight: 'bold',
      color: '#E91E63',
      textAlign: 'center',
      marginBottom: config.spacing.medium * 1.5,
    },
    nameInputContainer: {
      width: '100%',
      marginTop: config.spacing.medium * 1.5,
    },
    firstVisitTooltip: {
      position: 'absolute',
      top: config.spacing.small + 40, // Position below tutorial button
      left: config.spacing.medium,
      borderRadius: 20,
      width: 150,
      minHeight: 50,
      padding: 12,
      zIndex: 99999,
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    tooltipContent: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    tooltipCloseButton: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: '#A4D233',
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    tooltipText: {
      flex: 1,
      fontFamily: 'Roboto',
      fontWeight: '700',
      fontSize: avatarSelectionConfig.subtitleFontSize * 0.75,
      lineHeight: avatarSelectionConfig.subtitleLineHeight * 0.75,
      color: '#000000',
    },
    tooltipTriangle: {
      borderTopWidth: 12,
      borderRightWidth: 10,
      borderRightColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: 'transparent',
      position: 'absolute',
      left: 16,
      top: -12,
      transform: [{ rotate: '180deg' }],
    },
    nameInput: {
      backgroundColor: '#F5F5F5',
      borderRadius: config.spacing.small,
      padding: config.spacing.medium,
      fontSize: avatarSelectionConfig.subtitleFontSize,
      marginBottom: config.spacing.small,
    },
    characterCount: {
      fontSize: avatarSelectionConfig.subtitleFontSize * 0.75,
      color: '#999',
      marginBottom: config.spacing.small,
    },
    hintText: {
      fontSize: avatarSelectionConfig.subtitleFontSize * 0.75,
      color: '#999',
    },
    modalButtons: {
      flexDirection: 'row',
      gap: config.spacing.small,
      marginTop: config.spacing.medium * 1.5,
    },
    modalButton: {
      flex: 0.5,
      minWidth: config.spacing.medium * 6.25,
      paddingVertical: config.spacing.medium,
      paddingHorizontal: config.spacing.medium * 1.25,
      borderRadius: config.spacing.small,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalButtonPrimary: {
      flex: 1,
      minWidth: config.spacing.medium * 9.375,
    },
    modalButtonText: {
      fontSize: avatarSelectionConfig.subtitleFontSize,
      fontWeight: '600',
      color: '#424242',
    },
  })


