// @TODO: move into submodule?
// @TODO: this should be typed?
export const emojis = {
  good: '😎',
  happy: '😊',
  blah: '😑',
  sad: '😔',
  stressed: '😤',
  worried: '😟',
  fabulous: '😎',
  lazy: '🥱',
  iritable: '😒',
  angry: '😡',
  tired: '💤',
  cramps: '💥',
  bloating: '🎈',
  spots: '💢',
  headache: '⚡',
  sore_breasts: '🍒',
  bloated: '💨',
  back_pain: '🏋🏽‍♀️',
  okay: '👌🏽',
  'healthy food': '🍏',
  'good sleep': '🛏️',
  "couldn't sleep": '😴',
  'unhealthy food': '🍰',
  exercise: '🏃‍♀️',
  socialising: '👋',
  music: '🎧',
  study: '📖',
  video: '🍿',
  none: '🌂',
  light: '💧',
  medium: '💦',
  heavy: '☔',
  spotting: '🔹',
  torrential: '🔹',
}
