export const emojis = {
  good: '😎',
  happy: '😊',
  blah: '😑',
  sad: '😔',
  stressed: '😤',
  worried: '😟',
  fabulous: '😎',
  tired: '💤',
  cramps: '💥',
  bloating: '🎈',
  spots: '💢',
  headache: '⚡',
  sore_breasts: '🍒',
  'healthy food': '🍏',
  'good sleep': '🛏️',
  "couldn't sleep": '😴',
  'unhealthy food': '🍰',
  exercise: '🏃‍♀️',
  socialising: '👋',
  none: '🌂',
  light: '💧',
  medium: '💦',
  heavy: '☔',
  spotting: '🔹',
  torrential: '🔹',
}
