// THIS FILE IS AUTOGENERATED - DO NOT EDIT THIS MANUALLY
import { Locale } from "../";
import { StaticContent } from "../../../types";

import { en } from "./en";
import { fil } from "./fil";

export const liveContent: Record<Locale, StaticContent> = {
  en,
  fil,
};
