// THIS FILE IS AUTOGENERATED - DO NOT EDIT THIS MANUALLY
import { Locale } from '../'
import { StaticContent } from '../../../types'

import { en } from './en'
import { ph } from './ph'

export const liveContent: Record<Locale, StaticContent> = {
  en,
  ph,
}
